# Generated by Django 4.2.7 on 2023-11-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='remaining_stock',
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
